[package]
name = "sytems-challenge"
version = "0.1.0"
authors = ["Dinesh Kumar Ranganathan <dkr2@illinois.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "*"
native-tls = "*"
clap = "*"
